{
 "title": "Dashboard1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Recomendaciones",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "recommendations_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Valoraciones de usuarios",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(movie_ratings_total) by (stars)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_time_seconds_bucket[1m])) by (le)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}