global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'movie-recommendation'
    static_configs:
      - targets: ['app:8082']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']